
#builda por padrão para o target dev. Para mudar para o target prod, define a variavem de ambiente TARGET=prod
services:
  frontend:
    build:
      context: frontend
      target: ${TARGET:-dev}
    stdin_open: true
    restart: always
    networks:
      - react-nest
    ports:
      - 5173:5173
    depends_on:
      - backend


  backend:
    restart: always
    build:
      context: backend
      target: ${TARGET:-dev}
    depends_on:
      - mongo
    networks:
      - nest-mongo
      - react-nest
    ports:
      - 3000:3000

  mongo:
    container_name: mongo
    restart: always
    image: mongo:6.0.3
    volumes:
      - ~/server/volumes/mongo:/data/db
    networks:
      - nest-mongo
    ports:
      - 27017:27017

  whatsapp-api:
    container_name: whatsapp-api
    restart: always
    image: codechat/api:latest
    ports:
      - 8083:8083
    volumes:
      - ~/server/volumes/whatsapp-api:/codechat/instances
    command: ['node', './dist/src/main.js']
    networks:
      - nest-mongo
    environment:
      CONFIG_SESSION_PHONE_CLIENT: 'myface'
      AUTHENTICATION_TYPE: 'apikey'



networks:
  react-nest:
  nest-mongo:

