
#builda por padrão para o target dev. Para mudar para o target prod, define a variavem de ambiente TARGET=prod
services:
  frontend:
    build:
      context: frontend
      target: ${TARGET:-dev}
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - react-nest
    ports:
      - 5173:5173
    expose:
      - 5173
    depends_on:
      - backend


  backend:
    restart: always
    build:
      context: backend
      target: ${TARGET:-dev}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
    networks:
      - nest-mongo
      - react-nest
    ports:
      - 3000:3000
    expose:
      - 3000

  mongo:
    container_name: mongo
    restart: always
    image: mongo:6.0.3
    volumes:
      - ~/server/volumes/mongo:/data/db
    networks:
      - nest-mongo
    ports:
      - 27017:27017
    expose:
      - 27017

  whatsapp-api:
    container_name: whatsapp-api
    restart: always
    build:
      context: whatsapp-api
    volumes:
      - ~/server/volumes/whatsapp-api:/var/run/docker.sock
    networks:
      - nest-mongo
    ports:
      - 8083:8083
    expose:
      - 8083

networks:
  react-nest:
  nest-mongo:
