
#builda por padrão para o target dev. Para mudar para o target prod, define a variavem de ambiente TARGET=prod
services:
  frontend:
    container_name: myface_frontend
    build:
      context: frontend
      target: ${TARGET:-dev}
    stdin_open: true
    restart: always
    networks:
      - react-nest
    ports:
      - 3000:3000
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - backend


  backend:
    container_name: myface_backend
    restart: always
    build:
      context: backend
      target: ${TARGET:-dev}
    depends_on:
      - mongo
    networks:
      - nest-mongo
      - react-nest
    ports:
      - 3001:3001
    environment:
      - TZ=America/Sao_Paulo

  mongo:
    container_name: myface_mongo
    restart: always
    image: ${MONGO_IMAGE}
    volumes:
      - ~/server/volumes/mongo:/data/db
    networks:
      - nest-mongo
    ports:
      - 27017:27017
    environment:
      - TZ=America/Sao_Paulo
    env_file: .env

  whatsapp-api:
    container_name: whatsapp-api
    restart: always
    image: codechat/api:latest
    ports:
      - 8083:8083
    volumes:
      - ~/server/volumes/whatsapp-api/instances:/codechat/instances
      - ~/server/volumes/whatsapp-api/store:/codechat/store/
    command: ['node', './dist/src/main.js']
    networks:
      - nest-mongo
    environment:
      CONFIG_SESSION_PHONE_CLIENT: 'myface'
      AUTHENTICATION_TYPE: 'apikey'
      AUTHENTICATION_API_KEY: 't8OOEeISKzpmc3jjcMqBWYSaJsafdefer'
      TZ: 'America/Sao_Paulo'




networks:
  react-nest:
  nest-mongo:

