version: '3'
services:
  whatsapp-api:
    container_name: whatsapp-api
    restart: always
    image: codechat/api:latest
    ports:
      - 8083:8083
    volumes:
      - /home/anakin/server/volumes/whatsapp-api/instances:/codechat/instances
      - /home/anakin/server/volumes/whatsapp-api/store:/codechat/store/
    command: ['node', './src/main.js']
    networks:
      - myfaceapp_nest-mongo
    environment:
      CONFIG_SESSION_PHONE_CLIENT: 'myface'
      AUTHENTICATION_TYPE: 'apikey'
      AUTHENTICATION_API_KEY: 't8OOEeISKzpmc3jjcMqBWYSaJsafdefer'
      TZ: 'America/Sao_Paulo'

networks:
  myfaceapp_nest-mongo:
    external: true
